// Generated by the Blazor I18n Text compiler
namespace WebApplication1.Client.I18nText
{
    public partial class MyText : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Home"</summary>
        public string Home;

        /// <summary>"words"</summary>
        public string key;

        /// <summary>"Select Day"</summary>
        public string SelectDay;

        /// <summary>"Welcome to the Buster75"</summary>
        public string Welcome;
    }
}
